name: Gerar Cobrinha

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gerar animação da cobrinha

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar cobrinha preta
        uses: Platane/snk@v3
        with:
          github_user_name: eduardosanchez08
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
